name: test

on:
   push:
      branches:
         - "*"

jobs:
   unit-tests:
      runs-on: ubuntu-latest

      env:
         EXAMPLE_ENV: ${{ secrets.EXAMPLE_ENV }}
      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 16

         - name: Install pnpm
           run: |
              npm install -g pnpm

         - name: Install dependencies
           run: |
              pnpm install

         - name: Run unit tests
           run: |
              npm run test-github-action

   type-tests:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 16

         - name: Install pnpm
           run: |
              npm install -g pnpm

         - name: Install dependencies
           run: |
              pnpm install

         - name: Run type tests
           run: |
              npm run type-test-github-action
